version: '3'
services:
  api:
    build:
      context: .
    image: sleepmonitor.api
    container_name: sleepmonitor.api
    depends_on:
      - db
    environment:
      - NODE_ENV=docker_dev
      - SERVER_PORT=3333
     
    networks:
      - sleepmonitor_api
    ports:
      - '3333:3333'
      - '9229:9229'
    command:
      - "nodemon"
      - "--inspect=0.0.0.0"
      - "./server.js"
      - "--use-strict"
    volumes:
      - .:/src/app

  db:
    container_name: sleepmonitor.db
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd
      - PGDATA=/var/lib/postgresql/data/pg9.6
    networks:
      - sleepmonitor_api
    ports:
      - '32768:5432'

networks:
  sleepmonitor_api:
    driver: bridge
